import 'package:get_it/get_it.dart';
import 'package:supa_architecture/models/sub_system.dart';
import 'package:supa_architecture/models/tenant_sub_system_mapping.dart';
import 'package:supa_architecture/supa_architecture.dart';

export 'admin_type.dart';
export 'app_user.dart';
export 'app_user_group.dart';
export 'app_user_group_filter.dart';
export 'app_user_info.dart';
export 'app_user_sub_system_mapping.dart';
export 'attachment.dart';
export 'comment_reaction.dart';
export 'current_tenant.dart';
export 'date_type.dart';
export 'discussion.dart';
export 'enum_model.dart';
export 'file.dart';
export 'forgot_password_dto.dart';
export 'gender.dart';
export 'global_user.dart';
export 'image.dart';
export 'language.dart';
export 'latest_comment.dart';
export 'period.dart';
export 'request_history.dart';
export 'requisition_entity.dart';
export 'tenant.dart';
export 'timezone.dart';
export 'user_notification.dart';

void registerModels() {
  final getIt = GetIt.instance;

  getIt.registerFactory<AdminType>(AdminType.new);
  getIt.registerFactory<AppUser>(AppUser.new);
  getIt.registerFactory<CommentReaction>(CommentReaction.new);
  getIt.registerFactory<LastestComment>(LastestComment.new);
  getIt.registerFactory<Discussion>(Discussion.new);
  getIt.registerFactory<AppUserGroup>(AppUserGroup.new);
  getIt.registerFactory<AppUserInfo>(AppUserInfo.new);
  getIt.registerFactory<AppUserSubSystemMapping>(AppUserSubSystemMapping.new);
  getIt.registerFactory<CurrentTenant>(CurrentTenant.new);
  getIt.registerFactory<DateType>(DateType.new);
  getIt.registerFactory<EnumModel>(EnumModel.new);
  getIt.registerFactory<File>(File.new);
  getIt.registerFactory<ForgotPasswordDto>(ForgotPasswordDto.new);
  getIt.registerFactory<Gender>(Gender.new);
  getIt.registerFactory<GlobalUser>(GlobalUser.new);
  getIt.registerFactory<Image>(Image.new);
  getIt.registerFactory<Language>(Language.new);
  getIt.registerFactory<Period>(Period.new);
  getIt.registerFactory<RequestHistory>(RequestHistory.new);
  getIt.registerFactory<RequisitionEntity>(RequisitionEntity.new);
  getIt.registerFactory<SubSystem>(SubSystem.new);
  getIt.registerFactory<Tenant>(Tenant.new);
  getIt.registerFactory<TenantSubSystemMapping>(TenantSubSystemMapping.new);
  getIt.registerFactory<Timezone>(Timezone.new);
  getIt.registerFactory<UserNotification>(UserNotification.new);
}
