name: Flutter Library Test

on:
  push:
    branches:
      - main
      - v1
  pull_request:
    branches:
      - main
      - v1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0" # You can specify a specific version if needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Run Flutter tests
      - name: Run tests
        run: flutter test

      # Step 5: Analyze code
      - name: Run flutter analyze
        run: flutter analyze
